% General initialization code for the aggregation functions
% Use by eval('AggKineticsDisplayDataV16')

% Display some numbers:
disp ('~~~~~~~~~~~~~~~~~~~~~~~')
disp (['klpf = ' num2str(klpf) '               klmf = ' num2str(klmf)])
disp (['klpm = ' num2str(klpm) '               klmm = ' num2str(klmm)])
disp (['kap = ' num2str(kap) '                kam = ' num2str(kam)])
disp (['kn = ' num2str(kn)])
disp (['cnmRatio = ' num2str(cnmRatio)])
disp (['kbf = ' num2str(kbf)])
disp (['kbm = ' num2str(kbm)])
disp (['p00 = ' num2str(p00)])
disp (['y00 = ' num2str(y00)])
disp (['rs = ' num2str(rs) ])
disp (['rfm = ' num2str(rfm) ])
disp ('=========================')
disp (['clpf = ' num2str(clpf) '               clmf = ' num2str(clmf)])
disp (['clpm = ' num2str(clpm) '               clmm = ' num2str(clmm)])
disp (['cap = ' num2str(cap) '                cam = ' num2str(cam)])
disp (['cn = ' num2str(cn)])
disp (['cnm = ' num2str(cnm)])
disp (['cbf = ' num2str(cbf)])
disp (['cbm = ' num2str(cbm)])
disp (['p0 = ' num2str(p0)])
disp (['y0 = ' num2str(y0)])
disp (['crs = ' num2str(crs) '                crp = ' num2str(crp)])
disp (['crfm = ' num2str(crfm) '               crfp = ' num2str(crfp)])
disp (['v = ' num2str(v)])
disp ('~~~~~~~~~~~~~~~~~~~~~~~')
disp ('xxxxxxxxxxxxxxxxxxxxxxxxxxxxx')